import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileBarChart2, Download, Droplets, Wind, Thermometer, Sun, CheckCircle } from 'lucide-react';
import { ResponsiveContainer, XAxis, YAxis, CartesianGrid, Tooltip, AreaChart, Area } from 'recharts';
import { useAuth } from '../../hooks/useAuth';
import { useTheme } from '../../hooks/useTheme';
import { useArduinoData } from '../../hooks/useArduinoData';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;
const TOKEN_KEY = 'nomou_access_token';

function generateCSV(data: { time: string; soil: number; temp: number; humid: number; light: number }[]) {
  const header = 'Time,Soil Moisture (%),Temperature (°C),Humidity (%),Light Level (%)\n';
  const rows = data.map(r => `${r.time},${r.soil.toFixed(1)},${r.temp.toFixed(1)},${r.humid.toFixed(1)},${r.light.toFixed(1)}`).join('\n');
  return header + rows;
}

function downloadCSV(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function generatePDFContent(current: ReturnType<typeof useArduinoData>['current'], username: string) {
  return `NOMOU Environmental Report
Generated: ${new Date().toLocaleString()}
User: ${username}
Node: A1 — Al-Wafra Farm

=== CURRENT READINGS ===
Soil Moisture:  ${current.soil_pct}% (${current.soil_cat})
Temperature:    ${current.temperature.toFixed(1)}°C
Humidity:       ${current.humidity.toFixed(0)}% (${current.humidity_cat})
Light Level:    ${current.light_pct}% (${current.light_cat})

=== ASSESSMENT ===
${current.soil_pct < 30 ? '⚠ Soil moisture is LOW — consider irrigation' : '✓ Soil moisture is within optimal range'}
${current.temperature > 35 ? '⚠ Temperature is HIGH — heat stress risk' : '✓ Temperature is normal'}
${current.humidity < 40 ? '⚠ Humidity is LOW' : '✓ Humidity is normal'}

Generated by NOMOU Smart Environmental Monitoring
nomou.io`;
}

function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export default function PortalReports() {
  const { user } = useAuth();
  const { isDark } = useTheme();
  const { current, history } = useArduinoData();
  const [generating, setGenerating] = useState(false);
  const [reportType, setReportType] = useState('Weekly');
  const [format, setFormat] = useState('CSV');
  const [generated, setGenerated] = useState(false);
  const [savedReports, setSavedReports] = useState<{ id: string; name: string; date: string; type: string; format: string }[]>([]);

  // Load saved reports from Supabase
  useEffect(() => {
    const load = async () => {
      if (!user) return;
      const token = localStorage.getItem(TOKEN_KEY);
      const res = await fetch(`${SUPABASE_URL}/rest/v1/reports?user_id=eq.${user.id}&order=created_at.desc&select=*`, {
        headers: { 'apikey': SUPABASE_ANON_KEY, 'Authorization': `Bearer ${token ?? SUPABASE_ANON_KEY}` },
      });
      if (res.ok) {
        const data = await res.json();
        setSavedReports(data.map((r: Record<string,unknown>) => ({
          id: r.id as string, name: r.name as string,
          date: new Date(r.created_at as string).toLocaleDateString('en-GB', { day:'numeric', month:'short', year:'numeric' }),
          type: r.type as string, format: r.format as string,
        })));
      }
    };
    load();
  }, [user]);

  // Build chart data from Arduino history
  const chartData = history.labels.length > 0
    ? history.labels.map((time, i) => ({
        time, soil: history.soil[i] ?? 0, temp: history.temp[i] ?? 0,
        humid: history.humid[i] ?? 0, light: history.light[i] ?? 0,
      }))
    : Array.from({ length: 7 }, (_, i) => {
        const days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
        return { time: days[i], soil: 25 + Math.random()*15, temp: 28 + Math.random()*8, humid: 50 + Math.random()*20, light: 40 + Math.random()*40 };
      });

  const handleGenerate = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 1200));
    const reportName = `${reportType} Report — ${new Date().toLocaleDateString('en-GB', { day:'numeric', month:'short', year:'numeric' })}`;
    // Download file immediately
    if (format === 'CSV') {
      const csvData = chartData.map(d => ({ time: d.time, soil: d.soil, temp: d.temp, humid: d.humid, light: d.light }));
      downloadCSV(generateCSV(csvData), `nomou-report-${Date.now()}.csv`);
    } else {
      downloadText(generatePDFContent(current, user?.name ?? 'User'), `nomou-report-${Date.now()}.txt`);
    }
    // Save to Supabase
    const token = localStorage.getItem(TOKEN_KEY);
    if (user && token) {
      const res = await fetch(`${SUPABASE_URL}/rest/v1/reports`, {
        method: 'POST',
        headers: { 'Content-Type':'application/json', 'apikey': SUPABASE_ANON_KEY, 'Authorization': `Bearer ${token}`, 'Prefer':'return=representation' },
        body: JSON.stringify({ user_id: user.id, name: reportName, type: reportType, format, size: '< 1 MB' }),
      });
      if (res.ok) {
        const data = await res.json();
        if (data?.[0]) setSavedReports(prev => [{ id: data[0].id, name: reportName, date: new Date().toLocaleDateString('en-GB', { day:'numeric', month:'short', year:'numeric' }), type: reportType, format }, ...prev]);
      }
    } else {
      setSavedReports(prev => [{ id: Date.now().toString(), name: reportName, date: new Date().toLocaleDateString(), type: reportType, format }, ...prev]);
    }
    setGenerating(false);
    setGenerated(true);
    setTimeout(() => setGenerated(false), 3000);
  };

  const inputCls = `px-3 py-2.5 rounded-xl border text-sm font-medium outline-none appearance-none cursor-pointer transition-all ${isDark ? 'bg-white/5 border-white/10 text-white' : 'bg-white border-gray-200 text-gray-700'}`;

  return (
    <div className="p-4 sm:p-6 space-y-6">
      <div>
        <h2 className={`text-2xl font-black ${isDark ? 'text-white' : 'text-[#0a120e]'}`}>Reports</h2>
        <p className={`text-sm mt-1 ${isDark ? 'text-white/40' : 'text-gray-500'}`}>Live environmental data from your node</p>
      </div>

      {/* Live stats from Arduino */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { label: 'Soil Moisture', value: `${current.soil_pct}%`, icon: Droplets, color: '#03A9F4', trend: current.soil_cat },
          { label: 'Temperature',   value: `${current.temperature.toFixed(1)}°C`, icon: Thermometer, color: '#FF9800', trend: current.temperature > 35 ? 'High' : 'Normal' },
          { label: 'Humidity',      value: `${Math.round(current.humidity)}%`, icon: Wind, color: '#4CAF50', trend: current.humidity_cat },
          { label: 'Light Level',   value: `${current.light_pct}%`, icon: Sun, color: '#9C27B0', trend: current.light_cat },
        ].map(s => {
          const Icon = s.icon;
          return (
            <motion.div key={s.label} whileHover={{ y: -4 }}
              className={`rounded-2xl p-4 border ${isDark ? 'bg-white/5 border-white/10' : 'bg-white border-gray-100 shadow-sm'}`}>
              <div className="flex items-center gap-2 mb-2">
                <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ backgroundColor:`${s.color}20` }}>
                  <Icon size={14} style={{ color: s.color }} />
                </div>
                <span className={`text-[10px] uppercase tracking-wider ${isDark ? 'text-white/40' : 'text-gray-400'}`}>{s.label}</span>
              </div>
              <div className={`text-xl font-black font-mono ${isDark ? 'text-white' : 'text-[#0a120e]'}`}>{s.value}</div>
              <div className="text-xs font-medium mt-0.5 capitalize" style={{ color: s.color }}>{s.trend}</div>
            </motion.div>
          );
        })}
      </div>

      {/* Trend chart from Arduino history */}
      <div className={`rounded-2xl p-5 border ${isDark ? 'bg-white/5 border-white/10' : 'bg-white border-gray-100 shadow-sm'}`}>
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className={`font-bold ${isDark ? 'text-white' : 'text-[#0a120e]'}`}>Sensor Trends</h3>
            <p className={`text-xs ${isDark ? 'text-white/30' : 'text-gray-400'}`}>{history.labels.length > 0 ? `Last ${history.labels.length} readings` : 'Live data'}</p>
          </div>
          <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-green-primary/10 border border-green-primary/20">
            <span className="w-1.5 h-1.5 rounded-full bg-green-primary animate-pulse" />
            <span className="text-xs font-bold text-green-primary">LIVE</span>
          </div>
        </div>
        <div className="flex gap-3 mb-3 flex-wrap">
          {[{ color:'#0288D1', label:'Soil %' }, { color:'#E65100', label:'Temp °C' }, { color:'#2E7D32', label:'Humidity %' }].map(l => (
            <div key={l.label} className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-sm" style={{ background: l.color }}/><span className="text-xs text-gray-500">{l.label}</span></div>
          ))}
        </div>
        <ResponsiveContainer width="100%" height={200}>
          <AreaChart data={chartData}>
            <defs>
              <linearGradient id="gs" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0288D1" stopOpacity={0.3}/><stop offset="95%" stopColor="#0288D1" stopOpacity={0}/></linearGradient>
              <linearGradient id="gt" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#E65100" stopOpacity={0.3}/><stop offset="95%" stopColor="#E65100" stopOpacity={0}/></linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="3 3" stroke={isDark ? 'rgba(255,255,255,0.04)' : '#f0f0f0'} vertical={false} />
            <XAxis dataKey="time" tick={{ fontSize:10, fill: isDark ? 'rgba(255,255,255,0.3)' : '#9E9E9E' }} axisLine={false} tickLine={false} />
            <YAxis tick={{ fontSize:10, fill: isDark ? 'rgba(255,255,255,0.3)' : '#9E9E9E' }} axisLine={false} tickLine={false} />
            <Tooltip contentStyle={{ background: isDark ? '#0d1f12' : '#fff', border:'1px solid rgba(0,0,0,0.1)', borderRadius:12, fontSize:12 }} />
            <Area type="monotone" dataKey="soil"  stroke="#0288D1" fill="url(#gs)" strokeWidth={2} name="Soil %" dot={false} />
            <Area type="monotone" dataKey="temp"  stroke="#E65100" fill="url(#gt)" strokeWidth={2} name="Temp °C" dot={false} />
            <Area type="monotone" dataKey="humid" stroke="#2E7D32" fill="none"      strokeWidth={2} name="Humidity %" dot={false} />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      {/* Generate report */}
      <div className={`rounded-2xl p-5 border ${isDark ? 'bg-white/5 border-white/10' : 'bg-white border-gray-100 shadow-sm'}`}>
        <h3 className={`font-bold mb-4 ${isDark ? 'text-white' : 'text-[#0a120e]'}`}>Generate Report</h3>
        <div className="flex flex-wrap gap-3 items-end">
          <div>
            <label className={`text-xs font-bold uppercase tracking-wider mb-1.5 block ${isDark ? 'text-white/40' : 'text-gray-500'}`}>Type</label>
            <select value={reportType} onChange={e => setReportType(e.target.value)} className={inputCls}>
              {['Daily','Weekly','Monthly'].map(t => <option key={t}>{t}</option>)}
            </select>
          </div>
          <div>
            <label className={`text-xs font-bold uppercase tracking-wider mb-1.5 block ${isDark ? 'text-white/40' : 'text-gray-500'}`}>Format</label>
            <select value={format} onChange={e => setFormat(e.target.value)} className={inputCls}>
              <option>CSV</option>
              <option>PDF (Text)</option>
            </select>
          </div>
          <motion.button whileHover={{ scale:1.03 }} whileTap={{ scale:0.97 }}
            onClick={handleGenerate} disabled={generating}
            className="flex items-center gap-2 px-5 py-2.5 bg-green-primary text-white font-bold rounded-xl text-sm hover:bg-green-light transition-colors disabled:opacity-60">
            {generating ? <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <FileBarChart2 size={15} />}
            {generating ? 'Generating…' : 'Generate & Download'}
          </motion.button>
          {generated && (
            <motion.div initial={{ opacity:0, x:-10 }} animate={{ opacity:1, x:0 }}
              className="flex items-center gap-2 text-green-primary text-sm font-semibold">
              <CheckCircle size={15} /> Downloaded!
            </motion.div>
          )}
        </div>
      </div>

      {/* Past reports */}
      <div className={`rounded-2xl border overflow-hidden ${isDark ? 'bg-white/5 border-white/10' : 'bg-white border-gray-100 shadow-sm'}`}>
        <div className={`px-5 py-4 border-b ${isDark ? 'border-white/5' : 'border-gray-100'}`}>
          <h3 className={`font-bold ${isDark ? 'text-white' : 'text-[#0a120e]'}`}>Generated Reports</h3>
        </div>
        {savedReports.length === 0 ? (
          <div className={`py-10 text-center text-sm ${isDark ? 'text-white/30' : 'text-gray-400'}`}>
            No reports yet — generate your first report above.
          </div>
        ) : (
          <div className="divide-y divide-gray-50">
            {savedReports.map((r, i) => (
              <motion.div key={r.id} initial={{ opacity:0, y:6 }} animate={{ opacity:1, y:0 }} transition={{ delay: i * 0.04 }}
                className="flex items-center justify-between px-5 py-3.5 hover:bg-green-primary/5 transition-colors">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-green-primary/10 flex items-center justify-center">
                    <FileBarChart2 size={16} className="text-green-primary" />
                  </div>
                  <div>
                    <p className={`text-sm font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{r.name}</p>
                    <p className={`text-xs ${isDark ? 'text-white/40' : 'text-gray-400'}`}>{r.date} · {r.format}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${isDark ? 'bg-white/10 text-white/60' : 'bg-gray-100 text-gray-500'}`}>{r.type}</span>
                  <button onClick={() => alert('Re-generate this report to download again.')}
                    className="flex items-center gap-1 text-xs text-green-primary font-semibold hover:text-green-light transition-colors">
                    <Download size={13} /> Download
                  </button>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
